spring:
  application:
    name: ms-core-spa
  jackson:
    serialization:
      indent-output: true
      order-map-entries-by-keys: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

auth:
  access:
    secret: '#Secret#2024*@#Access#Develop'
    expiration-minutes: 5